config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  post "comments/create"
  delete "comments/destroy/:id", to: 'comments#destroy', as: "comments_destroy"
  get "posts/my_posts"
  get "posts/discussed_posts"
  resources :posts
  get '*path' => redirect('/')
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :body,:author_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, :body, :author_id,  presence: true
    paginates_per 5
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #before_action :authenticate_user!
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :avatar)}
         end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        new_author_id = current_user.id
        new_body = params["comment"]["body"]
        new_post_id = params["format"]
        Comment.create(body: new_body, author_id: new_author_id, post_id: new_post_id)
        Post.find_by(id: new_post_id).increment!(:comments_count,  1) if !new_body.empty?
        redirect_back fallback_location: @post
    end

    def destroy
        Comment.find_by(id: params[:id]).destroy
        Post.find_by(id: params[:post_id]).decrement!(:comments_count,  1)
        respond_to do |format|
          format.html { redirect_back fallback_location: @post, notice: "Comment was successfully destroyed." }
          format.json { head :no_content }
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.order(created_at: :desc).page(params[:page])
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = Comment.where(post_id: @post.id).to_a
    @new_comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params.merge(author_id: current_user.id))
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    Comment.where(post_id: @post.id).destroy_all
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post and its comments was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def my_posts
    @posts = Post.where(author_id: current_user.id).page(params[:page])
    render "my_posts"
  end

  def discussed_posts
    date = Date.today
    @posts = Post.where(:created_at => (date.beginning_of_day..date.end_of_day)).order(comments_count: :desc).limit(5)
    render "discussed_posts"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :author_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def user_avatar(user)
        if user.avatar.attached? then
            user.avatar
        else
            "/default_avatar.jpg"
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DotBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style>
      body { background-image: linear-gradient( 179.4deg,  rgba(253,240,233,1) 2.2%, rgba(255,194,203,1) 96.2% );
             background-attachment: fixed;
            }
      .without-footer{
            min-height: calc(100vh - 72px);
      }
    </style>
    <%= favicon_link_tag asset_path('/baseline_chat_bubble_outline_black_18dp.png') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="without-footer">
    <nav class="navbar navbar-expand-lg navbar-light bg-light ">
    <a class="navbar-brand mb-0" href="<%=root_url%>"><img src="/baseline_chat_bubble_outline_black_18dp.png" width="40" height="40" alt=".Textboard"> DotBoard </a>
    <% if controller_name != "registrations" && controller_name != "sessions" && controller_name != "mailer" then %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
              <a class="nav-link" href="<%= root_url %>"> All posts <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="<%= posts_discussed_posts_url %>"> Hot posts <span class="sr-only">(current)</span></a>
            </li>
            <% if current_user %>
            <li class="nav-item ">
              <a class="nav-link" href="<%= posts_my_posts_url %>"> My posts <span class="sr-only">(current)</span></a>
            </li>
            
            <% end %>
          
          <% if current_user %>
          <li class="nav-item dropdown">
            
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Current user: <%= current_user.name %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item"%>
              <div class="dropdown-divider "></div>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item"%>
            </div>
          </li>
          <li class="nav-item ">
              <a class="nav-link" href="<%= new_post_url %>"> Create a post <span class="sr-only">(current)</span></a>
            </li>
          <% else %>
            <%= link_to "Log in", new_user_session_path, class: "nav-link"%>
          <% end %>
          </ul>
      </div>
    <% end %>
    </nav>

    <% if controller_name == "posts" then %>
      <div class="container">
        <div class="row justify-content-center">
          <div class="bg-white col-lg-12 m-lg-5 p-md-5 shadow pt-3 pb-3" >
          <% if notice or alert then %>
            <div class="alert alert-primary alert-dismissible fade show col-md-6 offset-md-3 justify-content-center" role="alert">
                  <%= notice %><%= alert %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <% end %>
            <%= yield %>
          </div>
        </div>
      </div>
    <% else %>
    <div class="container">
      <div class="row justify-content-center">
          <div class="bg-white col-lg-5 m-lg-5 p-md-5 shadow pt-3 pb-3" >
          <% if notice or alert then %>
            <div class="alert alert-primary alert-dismissible fade show justify-content-center" role="alert">
                  <%= notice %><%= alert %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <% end %>
            <%= yield %>
          </div>
        </div>
      </div>  
    <% end %>

  </div>

  <footer class="footer bg-light p-4 ">
      <div class="container">
        <span class="text-muted">KTM, 2021</span>
      </div>
  </footer>

  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.label "Image for the post:"%>
    <%= f.file_field :image, class: "form-control-file mb-3" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-outline-success mb-3"  %>
  </div>
<% end %>

app/views/posts/discussed_posts.html.erb
<h1>Highly Discussed Posts<span class="text-muted"> from today</span></h1>
<hr>
<% if @posts.empty? %>
<p class="text-muted"> No posts yet! </p>
<% else %>
<% @posts.each do |post| %>
  <div class="card mb-3 <% if current_user && current_user.id == post.author_id.to_i%> 
                  border-primary
                  <% end %>">
  <% author = User.find_by(id: post.author_id)%>
  <div class="card-header pb-0 pt-3">
    <div class="row d-flex align-items-center">
      <%= image_tag user_avatar(author), width:"50", heigth:"50", class:"rounded mb-3 ml-2 " %>
      <h5 class="ml-2"><%= author.name %></h5>
    </div>
  </div>
  <%=  image_tag(post.image, class: "card-img-top") if post.image.attached?  %>
    <div class="card-body">
      <h5 class="card-title"><%=post.title%></h5>
      <p class="card-text"><%=post.body%></p>
      <footer class="blockquote-footer mb-3"> <%= post.created_at %></footer>
      <div class="btn-group">
          <a class="btn btn-outline-primary btn-group-toggle" href="<%= post_path(id: post.id)%>">Comments
          <span class="badge badge-pill badge-dark"><%= post.comments_count%></span></a>
          <% if current_user && current_user.id == post.author_id.to_i%>
          <%= link_to 'Edit', edit_post_path(post), class: "btn btn-outline-success btn-group-toggle"%>
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-group-toggle"%>
          <% end %>
      </div>
    </div>
  </div>
<% end %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<hr>
<%= render 'form', post: @post %>

<div class="btn-group ">
    <%= link_to 'Show', @post, class: "btn btn-outline-primary" %>
    <%= link_to 'Back', posts_path, class: "btn btn-outline-primary" %>
    <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-group-toggle"%>
</div>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<hr>
<% if @posts.empty? %>
<p class="text-muted"> No posts yet! </p>
<% else %>
<% @posts.each do |post| %>
  <div class="card mb-3 <% if current_user && current_user.id == post.author_id.to_i%> border-primary <% end %>">
  <% author = User.find_by(id: post.author_id)%>
  <div class="card-header pb-0 pt-3">
    <div class="row d-flex align-items-center">
      <%= image_tag user_avatar(author), width:"50", heigth:"50", class:"rounded mb-3 ml-2 " %>
      <h5 class="ml-2"><%= author.name %></h5>
    </div>
  </div>

  <%=  image_tag(post.image, class: "card-img-top") if post.image.attached?  %>
    <div class="card-body">
      <h5 class="card-title"><%=post.title%></h5>
      <p class="card-text"><%=post.body%></p>
      <footer class="blockquote-footer mb-3"> <%= post.created_at %></footer>
      <div class="btn-group">
          <a class="btn btn-outline-primary btn-group-toggle" href="<%= post_path(id: post.id)%>">Comments
          <span class="badge badge-pill badge-dark"><%= post.comments_count%></span></a>
          <% if current_user && current_user.id == post.author_id.to_i%>
          <%= link_to 'Edit', edit_post_path(post), class: "btn btn-outline-success btn-group-toggle"%>
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-group-toggle"%>
          <% end %>
      </div>
    </div>
  </div>
<% end %>
<div class="d-flex justify-content-center">
  <%= paginate @posts %>
</div>
<% end %>

app/views/posts/my_posts.html.erb
<h1>My Posts</h1>
<hr>
<% if @posts.empty? %>
<p class="text-muted"> No posts yet! </p>
<% else %>
<% @posts.each do |post| %>
  <div class="card mb-3 <% if current_user && current_user.id == post.author_id.to_i%> 
                  border-primary
                  <% end %>">
  <% author = User.find_by(id: post.author_id)%>
  <div class="card-header pb-0 pt-3">
    <div class="row d-flex align-items-center">
      <%= image_tag user_avatar(author), width:"50", heigth:"50", class:"rounded mb-3 ml-2 " %>
      <h5 class="ml-2"><%= author.name %></h5>
    </div>
  </div>
  <%=  image_tag(post.image, class: "card-img-top") if post.image.attached?  %>
    <div class="card-body">
      <h5 class="card-title"><%=post.title%></h5>
      <p class="card-text"><%=post.body%></p>
      <footer class="blockquote-footer mb-3"> <%= post.created_at %></footer>
      <div class="btn-group">
          <a class="btn btn-outline-primary btn-group-toggle" href="<%= post_path(id: post.id)%>">Comments
          <span class="badge badge-pill badge-dark"><%= post.comments_count%></span></a>
          <%= link_to 'Edit', edit_post_path(post), class: "btn btn-outline-success btn-group-toggle"%>
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-group-toggle"%>
      </div>
    </div>
  </div>
<% end %>
<div class="d-flex justify-content-center">
  <%= paginate @posts %>
</div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<hr>
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="card mb-3 <% if current_user && current_user.id == @post.author_id.to_i %> 
                  border-primary
                  <% end %>">
  <% author = User.find_by(id: @post.author_id)%>
    <div class="card-header pb-0 pt-3">
      <div class="row d-flex align-items-center">
        <%= image_tag user_avatar(author), width:"50", heigth:"50", class:"rounded mb-3 ml-2 " %>
        <h5 class="ml-2"><%= author.name %></h5>
      </div>
    </div>
  <%=  image_tag(@post.image, class: "card-img-top") if @post.image.attached?  %>
    <div class="card-body">
      <h5 class="card-title"><%=@post.title%></h5>
      <p class="card-text"><%=@post.body%></p>
      <% if current_user && current_user.id == @post.author_id.to_i%>
      <div class="btn-group">
          <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-outline-success btn-group-toggle"%>
          <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-group-toggle"%>
      </div>
      <% end %>
    </div>
  </div>
<div class="comments">
  <h5 class = "mb-3"> Comments: </h5>
  <% if @comments.empty? then %>
    <p class="text-muted"> No comments yet! </p>
  <% else %>
  <% @comments.each do |comment| %>
    <div class="card mb-3 <% if current_user && current_user.id == comment.author_id%> 
                  border-primary
                  <% end %>">
    <% author = User.find_by(id: comment.author_id)%>
    <div class="card-header pb-0 pt-3">
      <div class="row d-flex align-items-center">
        <%= image_tag user_avatar(author), width:"50", heigth:"50", class:"rounded mb-3 ml-2 " %>
        <h5 class="ml-2"><%= author.name %></h5>
      </div>
    </div>
      <div class="card-body">
        <p class="card-text"><%=comment.body%></p>
        <% if current_user && current_user.id == comment.author_id%>
          <div class="btn-group">
            <%= link_to 'Delete', comments_destroy_path(id: comment.id, post_id: @post.id) , method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-group-toggle"%>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <% end %>
  <% if current_user %>
    <h5> Add a new comment: </h5>
    <div class="card mb-3 border-dark">
        <div class="card-body">
          <%= simple_form_for @new_comment, url: comments_create_path(@post.id) do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
            <div class="form-inputs">
              <%= f.input :body, label: false%>
            </div>
            <div class="form-actions">
              <%= f.button :submit, class: "btn btn-outline-success "  %>
            </div>
          <% end %>
        </div>
      </div>
  </div>
  <% end  %>
<div class="btn-group">
  <%= link_to 'Back', posts_path, class: "btn btn-outline-primary " %>
</div>